### ISSUE TITLE
现在不能用了是怎么回事？

### ISSUE THREAD

**Issue by UryWu** [cyio/audio-only-bilibili#14]
点击图标没反应？？希望作者有时间更新下。

**Comment by cyio** [comment]
可以试试切到 360p/480p 是否可用

一两天审核更新的版本，会修复高码率下失效问题。

**Comment by cyio** [comment]
商店已更新

**Comment by Icy-Cat** [comment]
似乎又失效了，尝试切换低画质也无法使用，参考视频链接 https://www.bilibili.com/video/BV1ea4y1P7kj/

**Comment by cyio** [comment]
@Icy-Cat 我这用这个视频正常，不确定是不是他们有新的视频流域名了

**Comment by cyio** [comment]
@Icy-Cat 我这用这个视频正常，不确定是不是他们有新的视频流域名了
